Module4 task2
SergWulf/668021-keksobooking pull request #1
Opened 2019-01-24 10:19 UTC by SergWulf

2019-01-25 07:48 UTC, 4err requested changes
В форму нужно в экшн добавить ссылку на сервер академии из ТЗ. Так ты сразу сможешь проверить еще и валидность итоговой формы.

2019-01-25 07:48 UTC, 4err commented on js/map.js
> +if ((Number(roomNumber.options[roomNumber.selectedIndex].value) !== MAX_ROOMS) && (Number(capacity.options[capacity.selectedIndex].value) !== MAX_GUESTS)) {
Рекомендую прочитать вот эту статейку. 
https://isqua.ru/blog/2017/07/09/simplify-if-else/

Нужно разбить проверки на более мелкие и составить условия по проще.

2019-01-25 07:48 UTC, 4err commented on js/map.js
> +if ((Number(roomNumber.options[roomNumber.selectedIndex].value) !== MAX_ROOMS) && (Number(capacity.options[capacity.selectedIndex].value) !== MAX_GUESTS)) {
Ну и не забывай про циклы.

2019-01-31 20:41 UTC, SergWulf commented on js/map.js
> +if ((Number(roomNumber.options[roomNumber.selectedIndex].value) !== MAX_ROOMS) && (Number(capacity.options[capacity.selectedIndex].value) !== MAX_GUESTS)) {
Статья помогла, уменьшил в 2 раза с чем-то кол-во строк!

2019-02-01 06:20 UTC, 4err requested changes

2019-02-01 06:20 UTC, 4err commented on js/map.js
> +  var expressionWithMaxValue = ((Number(capacity.options[capacity.selectedIndex].value) === MAX_GUESTS) && (Number(roomNumber.options[roomNumber.selectedIndex].value) === MAX_ROOMS));
Давай еще упрощать код. 
Во-первых, строку с параметрами выбора, которая показывается пользователю, можно вынести в переменную или даже константу. Таким образом в случае правок нужно будет поменять сообщение только в одном месте. 

Во-вторых, вот в этих 2х переменных используются одинаковые условия, только с обратным знаком. 
Можно получить в переменную результат выражения: `(Number(roomNumber.options[roomNumber.selectedIndex].value) !== MAX_ROOMS)` и просто использовать логическое отрицание для этой же переменной. 

Настоло время для этой статьи: https://isqua.ru/blog/2016/08/14/takoi-prostoi-boolean/

2019-02-01 09:24 UTC, SergWulf commented on js/map.js
> +  var expressionWithMaxValue = ((Number(capacity.options[capacity.selectedIndex].value) === MAX_GUESTS) && (Number(roomNumber.options[roomNumber.selectedIndex].value) === MAX_ROOMS));
Ок, готово!

2019-02-02 07:32 UTC, merged